### ISSUE TITLE
License in config.json.example causes JSON parsing error

### ISSUE THREAD

**Issue by samryanuofl** [project-chip/certification-tool-cli#10]
I tried installing this and the first time I ran `cli.sh --help` I got the error:

```
Traceback (most recent call last):
  File "/home/sam/dev/certification-tool-cli/app/main.py", line 20, in <module>
    from commands import (
  File "/home/sam/dev/certification-tool-cli/app/commands/__init__.py", line 16, in <module>
    from .available_tests import available_tests
  File "/home/sam/dev/certification-tool-cli/app/commands/available_tests.py", line 22, in <module>
    from client import client
  File "/home/sam/dev/certification-tool-cli/app/client.py", line 17, in <module>
    from config import config
  File "/home/sam/dev/certification-tool-cli/app/config.py", line 40, in <module>
    config = Config.parse_file(config_file)
  File "pydantic/main.py", line 561, in pydantic.main.BaseModel.parse_file
  File "pydantic/parse.py", line 64, in pydantic.parse.load_file
  File "pydantic/parse.py", line 37, in pydantic.parse.load_str_bytes
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 2 (char 2)
```

I think this is because the license at the top of `config.json.example` (the lines starting with `#`) is invalid JSON. When I deleted that it worked.

**Comment by VaishaliAvhale** [comment]
I'm also facing the same issue.

**Comment by rquidute** [comment]
Closing this issue since it seems it was fixed here: https://github.com/project-chip/certification-tool-cli/pull/16
